In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_customers_dataset.csv")

orders = pd.read_csv( r"C:\Users\LENOVO\Downloads\archive\olist_orders_dataset.csv")

order_items = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_order_items_dataset.csv")

payments = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_order_payments_dataset.csv")

reviews = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_order_reviews_dataset.csv")

products = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_products_dataset.csv")

sellers = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_sellers_dataset.csv")

geolocation = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\olist_geolocation_dataset.csv")

category_translation = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\product_category_name_translation.csv")

In [3]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

In [4]:
for name, df in tables.items():
    print(name,":",df.shape)

customers : (99441, 5)
orders : (99441, 8)
order_items : (112650, 7)
payments : (103886, 5)
reviews : (99224, 7)
products : (32951, 9)
sellers : (3095, 4)
geolocation : (1000163, 5)
category_translation : (71, 2)

In [5]:
for name, df in tables.items():
    print("\n" + "="*60)
    print(name)
    print(df.columns.tolist())

============================================================
customers
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
orders
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
order_items
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
payments
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
reviews
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
products
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
sellers
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
geolocation
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
category_translation
['product_category_name', 'product_category_name_english']

In [6]:
for name, df in tables.items():
    print("\n" + "="*60)
    print(name)
    print(df.dtypes)

============================================================
customers
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

============================================================
orders
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

============================================================
order_items
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

============================================================
payments
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

============================================================
reviews
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

============================================================
products
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

============================================================
sellers
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

============================================================
geolocation
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

============================================================
category_translation
product_category_name            str
product_category_name_english    str
dtype: object

In [7]:
for name, df in tables.items():
    print("\n" + "="*60)
    print(name)
    print(df.isnull().sum())

============================================================
customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

============================================================
orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

============================================================
order_items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

============================================================
payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

============================================================
reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

============================================================
products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

============================================================
sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

============================================================
geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

============================================================
category_translation
product_category_name            0
product_category_name_english    0
dtype: int64

In [8]:
products[products.isnull().any(axis=1)]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [9]:
products[
    products["product_category_name"].notnull() &
    products[["product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]].isnull().any(axis=1)
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN

In [10]:
products[
    products["product_id"] == "09ff539a621711667c43eba6a3bd8466"
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN

In [11]:
for name, df in tables.items():
    print(name, ":", df.duplicated().sum())

customers : 0
orders : 0
order_items : 0
payments : 0
reviews : 0
products : 0
sellers : 0
geolocation : 261831
category_translation : 0

In [12]:
geolocation.shape

(1000163, 5)

In [13]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [14]:
geolocation["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [15]:
geo_zip_check = (
    geolocation
    .groupby("geolocation_zip_code_prefix")
    .agg(
        city_count=("geolocation_city", "nunique"),
        state_count=("geolocation_state", "nunique")
    )
    .reset_index()
)

geo_zip_check[geo_zip_check["city_count"] > 1].head(10)

   geolocation_zip_code_prefix  city_count  state_count
0                         1001           2            1
1                         1002           2            1
2                         1003           2            1
3                         1004           2            1
4                         1005           2            1
5                         1006           2            1
6                         1007           2            1
7                         1008           2            1
8                         1009           2            1
9                         1010           2            1

In [16]:
geo_zip_check[geo_zip_check["state_count"] > 1].head(10)

       geolocation_zip_code_prefix  city_count  state_count
367                           2116           2            2
1668                          4011           2            2
6506                         21550           1            2
6696                         23056           1            2
14664                        72915           3            2
15879                        78557           2            2
16146                        79750           1            2
16256                        80630           2            2

In [17]:
customers["customer_city"].value_counts().head(20)

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
niteroi                    849
santo andre                797
osasco                     746
santos                     713
goiania                    692
sao jose dos campos        691
fortaleza                  654
sorocaba                   633
recife                     613
florianopolis              570
Name: count, dtype: int64

In [18]:
customers["customer_city"].nunique()

4119

In [19]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [20]:
orders[date_columns].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [21]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

In [22]:
order_items["shipping_limit_date"].dtype

dtype('<M8[us]')

In [25]:
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

In [26]:
for col in review_date_columns:
    reviews[col] = pd.to_datetime(reviews[col])

In [27]:
print(reviews[review_date_columns].dtypes)

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [28]:
print("Orders:")
print(orders[date_columns].isnull().sum())

print("\nOrder Items:")
print(order_items["shipping_limit_date"].isnull().sum())

print("\nReviews:")
print(reviews[review_date_columns].isnull().sum())

Orders:
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Order Items:
0

Reviews:
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [29]:
print("customers:", customers["customer_id"].nunique(), len(customers))
print("orders:", orders["order_id"].nunique(), len(orders))
print("products:", products["product_id"].nunique(), len(products))
print("sellers:", sellers["seller_id"].nunique(), len(sellers))

customers: 99441 99441
orders: 99441 99441
products: 32951 32951
sellers: 3095 3095

In [30]:
%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
%pip install "psycopg[binary]" sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: psycopg[binary] in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (3.3.4)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (2026.3)
Requirement already satisfied: psycopg-binary==3.3.4 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (3.3.4)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
import psycopg
print(psycopg.__version__)

3.3.4

In [33]:
from sqlalchemy import create_engine, URL

username = "postgres"
password = os.getenv"POSTGRES_PASSWORD"
host = "localhost"
port = 5432
database = "ecommerce_sales_analysis"

url = URL.create(
    "postgresql+psycopg",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(url)

In [34]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for table_name, df in tables.items():
    df.to_sql(
        table_name,
        engine,
        if_exists="replace",
        index=False
    )
    print(f"{table_name} loaded successfully.")

customers loaded successfully.
orders loaded successfully.
order_items loaded successfully.
payments loaded successfully.
reviews loaded successfully.
products loaded successfully.
sellers loaded successfully.
geolocation loaded successfully.
category_translation loaded successfully.